const ProductData = [
  {
    id: 1,
    img: "./photos/body_massage_women.png",
    name: "body massage for women",
    decs: "this is the best product for women in 2200",
    price: 1550,
    inStoke: 4,
    rating: 1.5,
    reView: 9,
  },
  {
    id: 2,
    img: "./photos/gold_secissor.webp",
    name: "gold secissor for men ",
    decs: "this is the best product to trim your hair",
    price: 230,
    inStoke: 0,
    rating: 0.5,
    reView: 0,
  },
  {
    id: 3,
    img: "./photos/lip_cream_women.jpg",
    name: "lip cream for womrn",
    decs: "this is the best product for women to keep his lip wet in winter",
    price: 100,
    inStoke: 4,
    rating: 1.5,
    reView: 9,
  },
  {
    id: 4,
    img: "./photos/massage_cream_men.jpg",
    name: "massage cream for men",
    decs: "this is the best product for men in 2200",
    price: 1050,
    inStoke: 4,
    rating: 2.5,
    reView: 9,
  },
  {
    id: 5,
    img: "./photos/men_cream.avif",
    name: "men cream",
    decs: "this is the best product for men over 18+",
    price: 1000,
    inStoke: 4,
    rating: 5,
    reView: 10,
  },
  {
    id: 6,
    img: "./photos/message_cream_men.webp",
    name: "body massage for women",
    decs: "this is the best product for women in 2200",
    price: 1550,
    inStoke: 4,
    rating: 3,
    reView: 9,
  },
];

export default ProductData;
